version: '3.6'

services:
  phoenix:
    container_name: api_phoenix
    build:
      context: ./
      dockerfile: ./tools/docker/phoenix/Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - ${BASE_DIR}/:/var/www
    networks:
      - backend

  database:
    container_name: api_phoenix_db
    image: postgres:11-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./tools/sql:/docker-entrypoint-initdb.d
    networks:
      - backend

volumes:
  postgresql_data:

networks:
  backend:
