version: '3.6'

services:

  workspace:
    container_name: wss
    build: docker/workspace/
    tty: true
    volumes:
      - ${BASE_DIR}/:/workspace
    networks:
      - backend

  phoenix:
    container_name: phoenix
    build: docker/phoenix/
    ports:
      - "4000:4000"
    volumes:
      - ${BASE_DIR}/:/var/www
    networks:
      - backend

  database:
    container_name: postgresql
    image: postgres:9-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgresql_data:

networks:
  backend:
